# Generated by Django 3.2.6 on 2021-08-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=26, unique=True)),
                ('first_name', models.CharField(max_length=26)),
                ('middle_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(to='Auth.User', verbose_name="User's Friends")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
